### ISSUE TITLE
How were you able to do this.

### ISSUE THREAD

**Issue by notsilverhoft** [L3m0n-Cao/papa-sushiria#1]
I have been trying to run an swf on WAflash for about 3 months, how did you do it?

**Comment by L3m0n-Cao** [comment]
well i got it to work fully, you can have a look at
https://sushiria.l3m0n.me/

I found an updated version on a chinese website, which I pulled using wget,
and un-minify the code, and adjust it to work.

I can share you the source code i'm using on discord: L3m.#0727

**Comment by L3m0n-Cao** [comment]
the version on this repository is still broken, I have a working version
that private, hence why I asked you to add me on discord. ( L3m.#0727 ).

**Comment by notsilverhoft** [comment]
Cool, i will.

**Comment by notsilverhoft** [comment]
I have sent you a friend request on discord, I'm Silverhoft#5306

**Comment by funkymonkey123c3** [comment]
I'm also sending a freind request as whatdadawgdoin#5624

**Comment by Githuthelp** [comment]
Wait.. https://sushiria.l3m0n.me/ link doesn't work

**Comment by L3m0n-Cao** [comment]
I removed it

**Comment by unxw** [comment]
can i have the source code as well? i sent a friend request, you can see me with the username "everyone"

**Comment by unxw** [comment]
nevermind, i found a working solution as well, however it runs at a low fps. Does your waflash run at a higher fps? If so, please dm me on tiktok or insta @vanilahz

**Comment by unxw** [comment]
nvm it was bcz school chromebooks are slow
